### ISSUE TITLE
notifications type missing in shovel config ts

### ISSUE THREAD

**Issue by jawndiego** [indexsupply/code#254]
notifications is missing from integrations type in ts 
https://github.com/indexsupply/code/blob/5a050d5b2200359720b98dba088d0b07035fd71d/shovel-config-ts/src/index.ts#L137

as defined here:

https://github.com/indexsupply/code/blob/5a050d5b2200359720b98dba088d0b07035fd71d/dig/dig.go#L656

**Comment by ryandotsmith** [comment]
ty for the bug report.

fixed. but i should say here that I would like to automate the creation of this TS package so that this is impossible.

Ideally there is a command we can run that will generate TS from the config structs. Also, the config structs should have good code level documentation so that we can also generate the [docs web page](https://indexsupply.com/shovel/docs/#config-object).
